language: ruby
sudo: false

install:
- bundle install
- gem install html-proofer

script:
- bundle exec jekyll build
- htmlproofer ./_site/ --only-4xx

branches:
  only:
  - master
  - staging
  - trying

notifications:
  email: false
